title: ICMR Reproducibility
email: maau@itu.dk
description: > # this means to ignore newlines until "baseurl:"
  ICMR Reproducibility 2024

# Build settings
markdown: kramdown
kramdown:
  toc_levels: "2,3"
baseurl: "/website"
url: ""
